baseurl: /my_jekyll
url: 'http://lab.diogorusso.com'
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-sitemap
exclude:
  - /gulp
  - /node_modules
  - gulpfile.js
  - _assets
  - bower.json
  - Gemfile
  - Gemfile.lock
  - package.json
author: Diogo Russo
job: experience designer
title: Estúdio Berinjela | Criação
description: >-
  I'm a DESIGNER and STORYTELLER I help businesses, individuals and communities
  craft meaningful EXPERIENCES and PRODUCTS
logo: +logo.png
favico: /lib/img/_favicon.ico
avatar: +avatar.png
card: /lib/img/_site_card.jpg
email: hello@diogorusso.com
country: United States
region: California
city: Berkeley
site-structure: multipage
paginate: 5
paginate_home: /work
paginate_link: /work/page
paginate_path: '/work/page:num'
img-path: /lib/img
img-max-width: '1920'
collections:
  docs:
    output: true
defaults:
  - scope:
      path: ''
      type: pages
    values:
      layout: page/default
      dev-info: true
      foundation5: 1
      fullpage: 1
      isotope: 1
      scroll-to: 1
      animation-page: 1
      animation-scroll: 1
      fitivid: 1
      swipebox: 1
      preloader: 1
      top-nav: 1
      footer: 2
      sidebar: 1
      grid: 1
      mast-head: 1
      back-to-top: 1
      map: 1
  - scope:
      path: ''
      type: posts
    values:
      layout: post
      auto-scroll: false
      txt-color: dark
      hero: true
      hero-bg-color: '#000'
      title: TITLE DEFAULT
      cover: /lib/content/cover/post-default-cover.jpg
      description: DESCRIPTION DEFAULT
      tags:
        - journal
g-analytics: UA-59944728-3
fb-app-id: '915671155245552'
see-also:
  - 'http://work.diogorusso.com'
  - 'http://www.lucaszappa.com.br'
  - 'http://www.estudioberinjela.com.br'
social:
  - name: behance
    url: 'https://www.behance.net/diogorusso'
  - name: linkedin
    url: 'https://www.linkedin.com/in/diogorusso/en'
  - name: envelope-o
    url: 'mailto:contato@estudioberinjela.com.br'
